src/objects/AddCampaignMembersByReportSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Designed to match report id&apos;s to campaign id&apos;s. Used by apex report notification classes or scheduleable apex to automate adding contacts or leads from a report to a campaign when the report runs. The &apos;Name&apos; of each custom setting record must be the 15 character ID of the saved report that includes the contact or lead record ids to add as campaign members. The apex code looks up this campaign ID cross-reference based on the report it is subscribed to.</description>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <description>The 15 character campaign id, usually copied from the end of the URL of the campaign record.</description>
        <inlineHelpText>The 15 character campaign id, usually copied from the end of the URL of the campaign record.</inlineHelpText>
        <label>Campaign ID</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Member_Added_Status__c</fullName>
        <description>The Campaign Member Status to use if a contact or lead is being added new to the campaign (does not already exist as a member). If blank then Salesforce will use the default configured on the Campaign.</description>
        <inlineHelpText>The Campaign Member Status to use if a contact or lead is being added new to the campaign (does not already exist as a member). If blank then Salesforce will use the default configured on the Campaign.</inlineHelpText>
        <label>Campaign Member Added Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_Contact_or_Lead_ID_Column_Label__c</fullName>
        <description>The column label on the report that holds the contact or lead record id to add to the campaign. The report should only include at most one column with this label heading and the value must be the record id (not a text or formula field). Example, if the column label is &quot;Contact ID&quot; that report field must either pull from the Contact ID field (Contact.Id) or a lookup field to Contact object like OpportunityContactRole.ContactId. Same applies for Lead ID report columns.</description>
        <inlineHelpText>The column label on the report that holds the contact or lead record id to add to the campaign. The report should only include at most one column with this label heading and the value must be the record id or lookup field (not a text or formula field).</inlineHelpText>
        <label>Report Contact or Lead ID Column Label</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Add Campaign Members by Report Setting</label>
</CustomObject>

src/classes/AddCampaignMembersByReportBatchable.cls
/**
 * Developed by Doug Ayers (douglascayers.com)
 * https://github.com/DouglasCAyers/sfdc-add-campaign-members-by-report
 */
public with sharing class AddCampaignMembersByReportBatchable implements Database.Batchable<ID>, Database.Stateful {

    private ID reportId;
    private ID campaignId;
    private String campaignMemberStatus;

    // The report service paginates through all the records in the report
    // by making multiple invocations, this gets around the 2,000 record limit in Analytics API.
    // To do this it sorts the report by a column, ideally with unique values, and applies a filter
    // to get the next round of records greater than the last value seen in the previous iteration.
    // These variables are the column label and name in the report to use for this sorting purpose.
    // And for our adding campaign members purpose, should be a Contact ID or Lead ID column.
    private String columnLabel;
    private String columnName;

    // ----------------------------------------------------

    public AddCampaignMembersByReportBatchable( ID reportId ) {

        System.debug( 'AddCampaignMembersByReportBatchable.init' );

        // to avoid having to check 15 and 18 character ids, the custom setting name is supposed to be the 15 character id for the report
        AddCampaignMembersByReportSetting__c setting = AddCampaignMembersByReportSetting__c.getValues( String.valueOf( reportId ).left( 15 ) );

        if ( setting == null ) {
            throw new AddCampaignMembersByReportException( 'Missing custom setting AddCampaignMembersByReportSetting__c record with name "' + reportId + '"' );
        }

        Reports.ReportExtendedMetadata metadata = Reports.ReportManager.describeReport( reportId ).getReportExtendedMetadata();
        Map<String, String> columnLabelsToNamesMap = getIdColumnNamesByLabelsMap( metadata );

        if ( columnLabelsToNamesMap == null ) {
            throw new AddCampaignMembersByReportException( 'Report with id "' + reportId + '" is missing columns that reference record ids like Contact.Id or Lead.Id' );
        }

        String columnName = columnLabelsToNamesMap.get( setting.report_contact_or_lead_id_column_label__c );

        if ( String.isBlank( columnName ) ) {
            throw new AddCampaignMembersByReportException( 'Report with id "' + reportId + '" is missing expected column label "' + setting.report_contact_or_lead_id_column_label__c + '" that references a record id like Contact.Id or Lead.Id' );
        }

        this.reportId = reportId;
        this.campaignId = setting.campaign_id__c;
        this.campaignMemberStatus = setting.campaign_member_added_status__c;
        this.columnLabel = setting.report_contact_or_lead_id_column_label__c;
        this.columnName = columnName;

        System.debug( 'reportId=' + this.reportId );
        System.debug( 'campaignId=' + this.campaignId );
        System.debug( 'campaignMemberStatus=' + this.campaignMemberStatus );
        System.debug( 'columnLabel=' + this.columnLabel );
        System.debug( 'columnName=' + this.columnName );

    }

    // ----------------------------------------------------

    public Iterable<ID> start( Database.BatchableContext context ) {

        System.debug( 'AddCampaignMembersByReportBatchable.start: ' + context );

        Iterable<Id> reportRowIdIterable = new NPSP_ReportService.ReportRowIdIterableIterator( this.reportId, this.columnName );

        return (Iterable<ID>) reportRowIdIterable;
    }

    public void execute( Database.BatchableContext context, List<ID> recordIds ) {

        System.debug( 'AddCampaignMembersByReportBatchable.execute: ' + context );

        new AddCampaignMembersByReportService().addMembersToCampaign( recordIds, this.campaignId, this.campaignMemberStatus );

    }

    public void finish( Database.BatchableContext context ) {

        System.debug( 'AddCampaignMembersByReportBatchable.finish: ' + context );

    }

    // ----------------------------------------------------

    private Map<String, String> getIdColumnNamesByLabelsMap( Reports.ReportExtendedMetadata metadata ) {

        System.debug( 'getting id column names by labels map' );
        System.debug( metadata );

        Map<String, Reports.DetailColumn> reportColumns = metadata.getDetailColumnInfo();

        System.debug( reportColumns );

        Map<String, String> columnLabelsToNamesMap = new Map<String, String>();

        for ( Reports.DetailColumn column : reportColumns.values() ) {
            if ( Reports.ColumnDataType.ID_DATA == column.getDataType() ) {
                columnLabelsToNamesMap.put(
                    column.getLabel(),
                    column.getName()
                );
            }
        }

        System.debug( columnLabelsToNamesMap );

        return columnLabelsToNamesMap;
    }

    public class AddCampaignMembersByReportException extends Exception {}

}