src/objects/NamespaceSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Populated by install post-script to know what namespace prefix to use by our code when deployed in subscriber org. http://salesforce.stackexchange.com/questions/28974/determining-namespace-prefix-in-javascript-and-apex</description>
    <fields>
        <fullName>BarPrefix__c</fullName>
        <description>The namespace with double underscore suffix &apos;ns__&apos;</description>
        <inlineHelpText>The namespace with double underscore suffix &apos;ns__&apos;</inlineHelpText>
        <label>Bar Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DotPrefix__c</fullName>
        <description>The namespace with dot suffix &apos;ns.&apos;</description>
        <inlineHelpText>The namespace with dot suffix &apos;ns.&apos;</inlineHelpText>
        <label>Dot Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RawPrefix__c</fullName>
        <description>Just the namespace &apos;ns&apos;</description>
        <inlineHelpText>Just the namespace &apos;ns&apos;</inlineHelpText>
        <label>Raw Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Namespace Settings</label>
</CustomObject>

src/classes/AddCampaignMembersInstallHandler.cls
/**
 * Developed by Doug Ayers (douglascayers.com)
 * https://github.com/DouglasCAyers/sfdc-add-campaign-members-by-report
 */
public with sharing class AddCampaignMembersInstallHandler implements InstallHandler {

    // only for unit tests, this lets us spoof a
    // namespace to assert prefixes created correctly
    @TestVisible
    private String testNamespace { get; set; }

    public void onInstall( InstallContext context ) {

        // http://salesforce.stackexchange.com/questions/28974/determining-namespace-prefix-in-javascript-and-apex

        NamespaceSettings__c setting = NamespaceSettings__c.getOrgDefaults();

        String prefix = AddCampaignMembersInstallHandler.class.getName().substringBefore( 'AddCampaignMembersInstallHandler' ).substringBefore( '.' );

        if ( Test.isRunningTest() ) {
            prefix = testNamespace;
        }

        if ( String.isNotBlank( prefix ) ) {
            setting.rawPrefix__c = prefix;
            setting.dotPrefix__c = prefix + '.';
            setting.barPrefix__c = prefix + '__';
        }

        upsert setting;

    }

}